#cloud-config
password: kubevirt
chpasswd: { expire: False }
packages:
  - nginx
timezone: Europe/Zurich
write_files:
  - content: |
      user nginx;
      worker_processes auto;
      error_log /var/log/nginx/error.log;
      pid /run/nginx.pid;

      events {
        worker_connections 1024;
      }

      http {
          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
          '$status $body_bytes_sent "$http_referer" '
          '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile            on;
          tcp_nopush          on;
          tcp_nodelay         on;
          keepalive_timeout   65;
          types_hash_max_size 4096;

          include             /etc/nginx/mime.types;
          default_type        text/plain;

          server {
              listen       8080;
              server_name  _;
              root         /usr/share/nginx/html;

              # Load configuration files for the default server block.
              include /etc/nginx/default.d/*.conf;

              location /health {
                return 200 'ok';
              }

              location / {
                set $response 'Hallo Bärn (${hostname})';
                return 200 '${response}';
              }
          }
      }      
    path: /etc/nginx/nginx.conf
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
